<?php

namespace Autobus\Bundle\BusBundle\Repository;

/**
 * CronJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronJobRepository extends \Doctrine\ORM\EntityRepository
{
}
