<?php

namespace Autobus\Bundle\BusBundle\Repository;

/**
 * WebJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebJobRepository extends \Doctrine\ORM\EntityRepository
{
}
