autobus_bus_configuration:
    resource: "@AutobusBusConfigurationBundle/Resources/config/routing.yml"
    prefix:   /job

bus:
    resource: "@AutobusBusBundle/Resources/config/routing.yml"
    prefix:   /

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: job_index
        permanent: true
