<?php

namespace BusBundle\Repository;

/**
 * CronServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
