<?php

namespace BusBundle\Repository;

/**
 * QueueServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueueServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
