<?php

namespace BusBundle\Repository;

/**
 * ServiceCallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCallRepository extends \Doctrine\ORM\EntityRepository
{
}
