<?php

namespace BusBundle\Repository;

/**
 * WebServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
